### ISSUE TITLE
[Android] Chrome

### ISSUE THREAD

**Issue by Mehmet-I** [symbuzzer/Turkish-Ad-Hosts#10]
Merhaba Ali Bey,

Magisk modülü olarak kurduğum ad host maalesef Chrome uygulamasını etkilemiyor. Öncesinde adaway üzerinden de denemiştim. Diğer tarayıcılarda reklam yok sadece Chrome da var. Sıfırlayıp yeniden kurdum kaç sefer ama sonuç değişmedi.

![Screenshot_2023-05-22-13-21-13-358-edit_com.miui.home.jpg](https://github.com/symbuzzer/Turkish-Ad-Hosts/assets/63732211/4b21bcf4-895b-47cc-bad7-2ce312e042fb)

![Screenshot_2023-05-22-12-53-05-196_com.github.axet.filemanager.jpg](https://github.com/symbuzzer/Turkish-Ad-Hosts/assets/63732211/18161a6a-7d1a-4f54-ac11-327ee6ef35e6)

![Screenshot_2023-05-22-12-52-43-129_com.topjohnwu.magisk.jpg](https://github.com/symbuzzer/Turkish-Ad-Hosts/assets/63732211/046044fa-807b-47f8-a8bd-ff7e06bd96ed)

Aynı sorun chrome tabanlı bir diğer browser olan Kiwi'de de var.

![Screenshot_2023-05-22-21-28-28-656_com.kiwibrowser.browser.jpg](https://github.com/symbuzzer/Turkish-Ad-Hosts/assets/63732211/08f62de5-82f5-4a85-b73e-13ca8065a080)

**Comment by symbuzzer** [comment]
@Mehmet-I Merhaba. Bu sorun daha önce de birilerinin başına gelmişti. Chrome ayarlarıyla ilgili bir sıkıntı. Google hesabınla her oturum açtığında o hatalı ayarı da geri yüklüyor. Bu yüzden veri ve önbelleği temizlesen de sorun tekrar ortaya çıkıyor. Chrome ayarlarını gözden geçirebilir misin? Özellikle veri kullanımını azalt vb ayarları kapatıp yeniden sıfırlayarak kontrol edebilir misin?

**Comment by Mehmet-I** [comment]
Chromeu tamamen sıfırladım. Giriş de yapmadım sıfırladıktan sonra. Reklam gene de geldi. Daha önce hiç giriş yapmadığım chrome tabanlı diğer uygulama olan Kiwi'de de aynı sorun var. Romun bir ayarı mu buna sebep oluyor anlayamadım. Veri kullanımı ayarı Android chrome'da kaldırıldı sanırım bu ayar görünmüyor. Romda arıyorum şimdi aktif bir ayar var mı böyle diye.

**Comment by symbuzzer** [comment]
@Mehmet-I sorun çözüldü mü? Çözüldüyse nasıl çözüldü?

**Comment by Mehmet-I** [comment]
@symbuzzer Sorun çözülmedi. Uğraşsam da bir yolunu bulamadım. Farklı bir tarayıcıya geçtim.
