### ISSUE TITLE
Hızlıresim kuralı hakkında

### ISSUE THREAD

**Issue by tetku** [symbuzzer/Turkish-Ad-Hosts#11]
Ben geliştirici değilim, bu host dosyasının ne işe yaradığını bilmiyorum ancak bir şeyi fark ettim. Aşağıdaki kural Hızlıresim bağlantılarını bozmaz mı? 
https://github.com/symbuzzer/Turkish-Ad-Hosts/blob/34e41cf539068d40bb584e42c1625d40cd608631/hosts#L880

Reklam ağı olarak engellenmiş ancak Hızlıresim'in kendisi reklam ağı değil. Sadece resim barındırma sitesi. Çoğu web sitesi Hızlıresim'i resim barındırmak için kullanıyor. Örneğin alttaki site gibi

`https://renaultfanclub.com/renault-talisman-kulubu/108049-r-link2-haritalarina-gelismis-3d-grafikleri-ve-54-farkli-harita-rengi-secenegi-ekleme.html`

<details>
 <summary>Screenshot</summary>

![resim](https://github.com/symbuzzer/Turkish-Ad-Hosts/assets/110184059/df77f085-e82e-49bb-bf49-ad80ddfba4e3)

</details>

**Comment by symbuzzer** [comment]
Hocam merhaba. Geri bildiriminiz için teşekkür ederim. Bir karışıklık olmuş olabilir. Bugün gerekli incelemeleri yapıp yazarım buraya. Bir yanlışlık varsa da düzeltmiş oluruz hem

**Comment by symbuzzer** [comment]
Tekrardan merhaba, hatalı kaydı kaldırdım. Geri bildirim için tekrardan teşekkür ederim.
