### ISSUE TITLE
USOM Listeleri

### ISSUE THREAD

**Issue by methicodx** [symbuzzer/Turkish-Ad-Hosts#20]
Üstad @symbuzzer Merhaba,

Ulusal Siber Olaylara Müdahale Merkezi bazı siteler için liste oluşturmuş. Mümkünse [bu adresleri](https://www.usom.gov.tr/url-list.txt) de ekleyebilir misiniz.

Teşekkürler,

**Comment by symbuzzer** [comment]
@methicodx Merhaba. Bu listenin lisansı nedir? Telif konusunda sıkıntı yaşamayalım

**Comment by symbuzzer** [comment]
@methicodx geri dönüş sağlayabilecekmisiniz? yoksa issue'yu kapatmak durumunda kalacam?

**Comment by methicodx** [comment]
Merhaba üstad @symbuzzer 
Sitelerinde şöyle bir bilgi var ama siz daha iyi bilirsiniz:

Telif Hakları

USOM Web Sitesi’nin hazırlanmasında kullanılan tasarım, yöntem ve içerik konusundaki telif hakları USOM’a aittir. Üçüncü şahıs ve/veya firmalara ait materyaller dışında kalan, USOM Web Sitesine rekabet avantajı sağlayan bilgi ve materyallere dair tüm telif hakları, tescilli marka, patent ve diğer mülkiyet hakları USOM’a aittir.

USOM Web Sitesinde herhangi bir şekilde reklam sunulmamaktadır. Sitede yer alan; logo, marka, veri dosyası, yazılı metin, bilgi, haber, görüş, tavsiye, reklam, ilan, ses, müzik, video, fotoğraf, görsel ve benzeri içeriğin bir kısmı USOM, bir kısmı da diğer kaynaklardan sağlanarak yayınlanabilir. USOM, içeriği ve hizmet koşullarını haber vermeden değiştirme hakkına sahiptir.

Ayrıca veri paylaşımıyla ilgili api sayfası açmışlar: https://www.usom.gov.tr/api/

Kullanıcı, USOM’un işbu Gizlilik Politikası ve Kullanım Koşullarında değişiklik yapabileceğini, yapılan değişikliklerin değişiklik tarihinden itibaren geçerli olacağını bildiğini kabul etmektedir.

**Comment by symbuzzer** [comment]
@methicodx geri dönüş için teşekkür ederim. Ancak 2 sebepten ötürü eklemem mümkün görünmüyor. İlki gördüğün üzere lisans durumu çok belirsiz ve kısıtlı görünüyor. Diğeri ise bu liste engelli sitelere ilişkin. Turkish Ad Hosts'un amacı izleme ağlarını engellemek. Anlayış göstereceğini düşünüyorum. Katkıların için teşekkür ederim.

**Comment by methicodx** [comment]
> @methicodx geri dönüş için teşekkür ederim. Ancak 2 sebepten ötürü eklemem mümkün görünmüyor. İlki gördüğün üzere lisans durumu çok belirsiz ve kısıtlı görünüyor. Diğeri ise bu liste engelli sitelere ilişkin. Turkish Ad Hosts'un amacı izleme ağlarını engellemek. Anlayış göstereceğini düşünüyorum. Katkıların için teşekkür ederim.

Ben teşekkür ederim üstad
