### ISSUE TITLE
wrong zipUrl in update.json

### ISSUE THREAD

**Issue by IzzySoft** [symbuzzer/Turkish-Ad-Hosts#21]
The current `update.json` points `zipURL` to `turkish-ad-hosts-magisk-kernelsu-module.zip` – however, there is no such file at the release, it's named slightly different: `turkish-ad-hosts-magisk-kernelsu-apatch-module.zip` (i.e. "injecting" the term "apatch"). Could you please fix/align this? Thanks in advance!

**Comment by symbuzzer** [comment]
Thanks for reporting. I made changes for APatch and forgot some smooth transition stuff. Will fix today

**Comment by symbuzzer** [comment]
Should be fixed?

**Comment by IzzySoft** [comment]
> Should be fixed?

Let me try…

    [2024/01/13 17:28:19] Sync INFO: update: [Turkish-Ad-Hosts] -> update to v24011207 (24011207)

Yupp, thanks!

In case you wonder where that line comes from: your module is in [my Magisk repo](https://apt.izzysoft.de/magisk) for FOSS modules, so one can obtain/update it via the [MRepo](https://apt.izzysoft.de/packages/com.sanmer.mrepo/) module manager. So that's from the logs of [its updater/managment software](https://github.com/ya0211/magisk-modules-repo-util).
