### ISSUE TITLE
cdn.taboola.com

### ISSUE THREAD

**Issue by eniscatak** [symbuzzer/Turkish-Ad-Hosts#22]
Hello.  Xiaomi Wallpaper Carousel application changes the lock screen wallpaper according to the topics chosen by the user.  Unfortunately, an address in the host file prevents this wallpaper change and the use of the application.  I added the address in the title section that prevents this application from working properly.

**Comment by symbuzzer** [comment]
Thanks for feedback, testing...

**Comment by symbuzzer** [comment]
Removed from list, thanks for reporting
