### ISSUE TITLE
www.youtube.com/watch?v(anynumber)/ and www.youtube.com or yt.be

### ISSUE THREAD

**Issue by enessmr** [symbuzzer/Turkish-Ad-Hosts#23]
Ads still come out. Fix that issue. Else, i use other adblockers. We know ads are s#itty. (I watched a meme ad on YouTube and fix that sh#t.)

**Comment by ramazansancar** [comment]
Just using this list will never be enough. If you wish, you can have an ad-free experience by using the ad lists in the guide I created. @enessmr 

My Repo: https://github.com/ramazansancar/notes/blob/main/ublock.MD

If you are using Pi-Hole, I have a list in it, you can find it in the repo.

**Comment by symbuzzer** [comment]
> Ads still come out. Fix that issue. Else, i use other adblockers. We know ads are s#itty. (I watched a meme ad on YouTube and fix that sh#t.)

It is not possible to block YouTube ads with the hosts file method. For this reason I am closing the issue.

**Comment by ramazansancar** [comment]
> > Ads still come out. Fix that issue. Else, i use other adblockers. We know ads are s#itty. (I watched a meme ad on YouTube and fix that sh#t.)
> 
> It is not possible to block YouTube ads with the hosts file method. For this reason I am closing the issue.

With Ublock, I can experience YouTube without seeing any ads. I advise. I recommend [LibreTube](https://libretube.dev/) for mobile.

**Comment by symbuzzer** [comment]
> > > Ads still come out. Fix that issue. Else, i use other adblockers. We know ads are s#itty. (I watched a meme ad on YouTube and fix that sh#t.)
> > 
> > 
> > It is not possible to block YouTube ads with the hosts file method. For this reason I am closing the issue.
> 
> With Ublock, I can experience YouTube without seeing any ads. I advise. I recommend [LibreTube](https://libretube.dev/) for mobile.

ublock also hide/disable elements, http get variables etc. it isnt include only hosts files

**Comment by enessmr** [comment]
@symbuzzer i use android

**Comment by ramazansancar** [comment]
> @symbuzzer i use android

For an ad-free and tracking-free YouTube experience, you can check these out:
- https://libretube.dev/
- https://newpipe.net/
- https://piped.video/
- https://redirect.invidious.io/

I actively use LibreTube. Although it does not load videos as instantly as YouTube, it offers a perfect experience. @enessmr

**Comment by enessmr** [comment]
Is there any login adfree UTube? YouTube: @Many_MC

**Comment by ramazansancar** [comment]
You can review what I posted. @enessmr
