### ISSUE TITLE
[Android] Tabii

### ISSUE THREAD

**Issue by Sauth-09** [symbuzzer/Turkish-Ad-Hosts#24]
Android'de Trt'nin Tabii uygulaması açılıyor ama herhangi bir video açılmıyor. Video yüklenme kısmında takılı kalıyor.

**Comment by Sauth-09** [comment]
![5736f5a5-6b27-4911-8eda-82ad05787c33](https://github.com/symbuzzer/Turkish-Ad-Hosts/assets/174242027/7d496d9d-aa0b-40eb-851c-2941cd638938)
![219f3628-5b04-427d-bc4a-dc1194911b70](https://github.com/symbuzzer/Turkish-Ad-Hosts/assets/174242027/2d10a43c-06b2-4b9d-a1f3-a8c84aea0d19)

**Comment by a-cakmak** [comment]
Windows da durum aynı.

**Comment by Sauth-09** [comment]
> Windows için de durum aynı.

Windowsta adguard ve ublock eklenti kullanıyorum sadece, bu şekilde sorun yok.

**Comment by a-cakmak** [comment]
Ali Bey'in Windows için hazırladığı bat dosyası için söyledim. Bu host dosyası kullanılmazsa dediğiniz gibi sorun olmuyor.

**Comment by hurgir** [comment]
sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi https://github.com/AdguardTeam/AdguardFilters/issues/181795 https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10

**Comment by symbuzzer** [comment]
> sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi [AdguardTeam/AdguardFilters#181795](https://github.com/AdguardTeam/AdguardFilters/issues/181795) https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10

Emin misiniz?

**Comment by hurgir** [comment]
> > sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi [AdguardTeam/AdguardFilters#181795](https://github.com/AdguardTeam/AdguardFilters/issues/181795) https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10
> 
> Emin misiniz?

adguarda böyle bir problem rapor edilmiş ve başlıkta belirtilen sorun var tvde tabii uygulaması yükleyemediğim için kontrol edemedim.

**Comment by symbuzzer** [comment]
> > > sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi [AdguardTeam/AdguardFilters#181795](https://github.com/AdguardTeam/AdguardFilters/issues/181795) https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10
> > 
> > 
> > Emin misiniz?
> 
> adguarda böyle bir problem rapor edilmiş ve başlıkta belirtilen sorun var tvde tabii uygulaması yükleyemediğim için kontrol edemedim.

Güncelledim, deneyebilir misiniz?

**Comment by Sauth-09** [comment]
> > > > sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi [AdguardTeam/AdguardFilters#181795](https://github.com/AdguardTeam/AdguardFilters/issues/181795) https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10
> > > 
> > > 
> > > Emin misiniz?
> > 
> > 
> > adguarda böyle bir problem rapor edilmiş ve başlıkta belirtilen sorun var tvde tabii uygulaması yükleyemediğim için kontrol edemedim.
> 
> Güncelledim, deneyebilir misiniz?

Denedim, hala açmıyor videoları.

**Comment by Sauth-09** [comment]
> > > > sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi [AdguardTeam/AdguardFilters#181795](https://github.com/AdguardTeam/AdguardFilters/issues/181795) https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10
> > > 
> > > 
> > > Emin misiniz?
> > 
> > 
> > adguarda böyle bir problem rapor edilmiş ve başlıkta belirtilen sorun var tvde tabii uygulaması yükleyemediğim için kontrol edemedim.
> 
> Güncelledim, deneyebilir misiniz?

Şimdi denedim, hala açmıyor videoları.

**Comment by Sauth-09** [comment]
> > > > > sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi [AdguardTeam/AdguardFilters#181795](https://github.com/AdguardTeam/AdguardFilters/issues/181795) https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10
> > > > 
> > > > 
> > > > Emin misiniz?
> > > 
> > > 
> > > adguarda böyle bir problem rapor edilmiş ve başlıkta belirtilen sorun var tvde tabii uygulaması yükleyemediğim için kontrol edemedim.
> > 
> > 
> > Güncelledim, deneyebilir misiniz?
> 
> Şimdi denedim, hala açmıyor videoları.

**Comment by hurgir** [comment]
> > > > > sorunun muhtemel kaynağı imasdk.googleapis.com adresinin engellenmesi [AdguardTeam/AdguardFilters#181795](https://github.com/AdguardTeam/AdguardFilters/issues/181795) https://github.com/AdguardTeam/AdguardFilters/blob/master/TurkishFilter/sections/allowlist.txt#L10
> > > > 
> > > > 
> > > > Emin misiniz?
> > > 
> > > 
> > > adguarda böyle bir problem rapor edilmiş ve başlıkta belirtilen sorun var tvde tabii uygulaması yükleyemediğim için kontrol edemedim.
> > 
> > 
> > Güncelledim, deneyebilir misiniz?
> 
> Şimdi denedim, hala açmıyor videoları.

Tarayıcı üzerinden denedim ve sorun bu filtre listesi için çözülmüş görünüyor. @Sauth-09 sizde imasdk.googleapis.com adresini kullanan farklı dns listeleri mevcutsa sorun onlardan da kaynaklı olabilir.

**Comment by a-cakmak** [comment]
Mobil düzeldi.
