### ISSUE TITLE
img.ekstat.com

### ISSUE THREAD

**Issue by ramazansancar** [symbuzzer/Turkish-Ad-Hosts#25]
**Buraya gerekçe yazınız / Write your reason here:**
Ekşi Sözlükte kullanıcıların üye görselleri bu bağlantıdan alınıyor. O yüzden ilgili alanlar yüklenmiyor.

![image](https://github.com/user-attachments/assets/e3442e78-e27e-46dc-b773-48d8e358cb21)

![image](https://github.com/user-attachments/assets/087ead62-69dd-430d-a4cd-9b2467522f24)

**Comment by symbuzzer** [comment]
kaldırıyorum, umarım kaldırdıktan sonra reklam görmeyiz, yoksa geri eklemem gerekecek. geri bildirim için teşekkür ederim
