### ISSUE TITLE
www2.hm.com/tr

### ISSUE THREAD

**Issue by HolyDemonz** [symbuzzer/Turkish-Ad-Hosts#26]
Filtre listesi; beden tablosu ve mağazadaki stok bilgisini engelliyor.

**Comment by symbuzzer** [comment]
@HolyDemonz merhaba. hangi site için?

**Comment by HolyDemonz** [comment]
hm.com

**Comment by symbuzzer** [comment]
@HolyDemonz sadece bir kaç test için kısa bir süre gerekiyor. Hemen dönüş yapacağımı umuyorum

**Comment by symbuzzer** [comment]
@HolyDemonz çoktan kaldırmışım. sorun hala devm ediyor mu? etmiyorsa issue'ye kapatabilir misiniz?
