### ISSUE TITLE
Blocking Ad blocker detected notification

### ISSUE THREAD

**Issue by Not-programerr** [symbuzzer/Turkish-Ad-Hosts#27]
Hocam bazı sitelerde adblock iptal et diye pop up çıkıyor ve içeriği göstermiyor. Onu engellemek için şöyle bir host dosyası buldum. Bunu nasıl ekleriz sizin modüle? Host([url](https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=rawlist))

**Comment by symbuzzer** [comment]
Merhaba. Bunu modüle eklemenin bir yolu yok. hosts dosyasının çalışma mantığına uygun değil
